apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-3
data:
  nginx.conf: |
    server {
        listen 80;
        location / {
            return 200 'Hello from NGINX Server THREE (Cell ID Range 300-399)!';
            add_header Content-Type text/plain;
        }
    }