apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: nginx-server-template
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-server-2
      - op: replace
        path: /spec/selector/matchLabels/app
        value: nginx-server-2
      - op: replace
        path: /spec/template/metadata/labels/app
        value: nginx-server-2
      - op: replace
        path: /spec/template/spec/volumes/0/configMap/name
        value: nginx-config-2
  - target:
      kind: Service
      name: nginx-service-template
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-service-2
      - op: replace
        path: /spec/selector/app
        value: nginx-server-2
  - target:
      kind: ConfigMap
      name: nginx-config-template
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-config-2
patchesStrategicMerge:
  - nginx-config-2-patch.yaml