apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-2
data:
  nginx.conf: |
    server {
        listen 80;
        location / {
            return 200 'Hello from NGINX Server TWO (Cell ID Range 200-299)!';
            add_header Content-Type text/plain;
        }
    }