apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

# Apply patches to customize the deployment and service for server 1
patches:
  # Patch to rename Deployment
  - target:
      kind: Deployment
      name: nginx-server-template
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-server-1
      - op: replace
        path: /spec/selector/matchLabels/app
        value: nginx-server-1
      - op: replace
        path: /spec/template/metadata/labels/app
        value: nginx-server-1
      # Link to the specific ConfigMap for this server (which we will also rename/patch)
      - op: replace
        path: /spec/template/spec/volumes/0/configMap/name
        value: nginx-config-1

  # Patch to rename Service
  - target:
      kind: Service
      name: nginx-service-template
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-service-1
      - op: replace
        path: /spec/selector/app
        value: nginx-server-1

  # Patch to rename the ConfigMap generated by the base
  - target:
      kind: ConfigMap
      name: nginx-config-template
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-config-1

patchesStrategicMerge:
  - nginx-config-1-patch.yaml