apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

configMapGenerator:
  - name: nginx-config-1
    literals:
      - nginx.conf=server { listen 80; location / { return 200 'Hello from NGINX Server ONE (Cell ID Range 100-199)!'; add_header Content-Type text/plain; } }

patches:

  # --- PATCH FOR DEPLOYMENT ---
  - target:
      kind: Deployment
      name: nginx-server-template
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-server-1
      - op: replace
        path: /spec/selector/matchLabels/app
        value: nginx-server-1
      - op: replace
        path: /spec/template/metadata/labels/app
        value: nginx-server-1
      - op: replace
        path: /spec/template/spec/volumes/0/configMap/name
        value: nginx-config-1

  # --- PATCH FOR SERVICE ---
  - target:
      kind: Service
      name: nginx-service-template
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-service-1
      - op: replace
        path: /spec/selector/app
        value: nginx-server-1

  # --- PATCH FOR INGRESS ---
  - target:
      kind: Ingress
      name: nginx-ingress-template
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-ingress-1
      - op: replace
        path: /spec/rules/0/host
        value: nginx1.yourdomain.com # REPLACE with a unique hostname (e.g., your name or initials)
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: nginx-service-1