apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Point to the common base templates
bases:
  - ../../base

# Generate a unique ConfigMap for this server from the base template
configMapGenerator:
  - name: nginx-config-1 # This will be the name of the ConfigMap for server 1
    files:
      - ../../base/nginx-config-template.conf
    literals: # Inject the unique content via literals
      - nginx.conf=server { listen 80; location / { return 200 'Hello from NGINX Server ONE (Cell ID Range 100-199)!'; add_header Content-Type text/plain; } }

# Apply patches to customize the deployment and service for server 1
patches:
  - target:
      kind: Deployment
      name: nginx-server-template # Target the generic name from base
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-server-1
      - op: replace
        path: /spec/selector/matchLabels/app
        value: nginx-server-1
      - op: replace
        path: /spec/template/metadata/labels/app
        value: nginx-server-1
      - op: replace
        path: /spec/template/spec/volumes/0/configMap/name
        value: nginx-config-1 # Link to this component's specific ConfigMap
  - target:
      kind: Service
      name: nginx-service-template
    patch: |-
      - op: replace
        path: /metadata/name
        value: nginx-service-1
      - op: replace
        path: /spec/selector/app
        value: nginx-server-1