apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-1
data:
  nginx.conf: |
    server {
        listen 80;
        location / {
            return 200 'Hello from NGINX Server ONE (Cell ID Range 100-199)!';
            add_header Content-Type text/plain;
        }
    }